### PR TITLE
Adjust `Stack` and `StackId` to better model the "any" stack

### LINKED ISSUE #147: Incorrect data model for StackId
https://github.com/Malax/libcnb.rs/commit/034b2a2f4be62f08ced2ed34a4c3a3ab06b521c4 changed `StackId` so that `*` is a valid `StackId`, which is incorrect.

There can't be a stack named `*`, but you can specify `*` in `buildpack.toml` to indicate that the buildpack is compatible with any stack. Those are very different things.

We should revert `StackId` to its previous implementation and introduce a new type that is used in the buildpack descriptor to model the "compatible with any stack" case. An enum like this comes to mind:

```rust
enum StackCompatibility {
    Any,
    Specific<Vec<StackId>>
}
```

GUS-W-10204027.

### PR DESCRIPTION
**Pull request by edmorley**
Previously the "any" stack was modelled as a `Stack` with a `StackId` of `"*"`, and an empty `Vec` of mixins, which does not accurately model the spec:
https://github.com/buildpacks/spec/blob/buildpack/0.6/platform.md#stack-id
https://github.com/buildpacks/spec/blob/buildpack/0.6/buildpack.md#buildpack-implementations

Now:
- `Stack` is an enum with `Any` and `Specific` variants.
-  `StackId` no longer permits IDs of `*`, since `Stack::Any` should be used instead.
- `BuildpackTomlError::InvalidStarStack` has been replaced by `BuildpackTomlError::InvalidAnyStack`.

Fixes #147.
GUS-W-10204027.

### CODE REVIEW

File: libcnb-data/src/buildpack.rs [hunk 1]
```diff
@@ -282,6 +288,8 @@ pub enum BuildpackTomlError {
 mod tests {
     use super::*;
 
+    type GenericBuildpackToml = BuildpackToml<Option<toml::value::Table>>;
```
Comment (edmorley) [inline libcnb-data/src/buildpack.rs:291]: I'll update the existing tests in this file to use this new type (and other test cleanup) after this merges.

File: libcnb-data/src/buildpack.rs [hunk 2]
```diff
@@ -260,16 +266,16 @@ libcnb_newtype!(
...
 
 #[derive(thiserror::Error, Debug)]
 pub enum BuildpackTomlError {
     #[error("Found `{0}` but value MUST be in the form `<major>.<minor>` or `<major>` and only contain numbers.")]
     InvalidBuildpackApi(String),
 
-    #[error("Stack with id `*` MUST not contain mixins. mixins: [{0}]")]
-    InvalidStarStack(String),
+    #[error("Stack with id `*` MUST NOT contain mixins, however the following mixins were specified: {0}")]
+    InvalidAnyStack(String),
```
Comment (Malax) [inline libcnb-data/src/buildpack.rs:278]: Ideally, this would not be a `String` but a `Vec<String>` (or `Vec<Mixin>` when we come to it). I don't know from the top of my head if `thiserror` can deal with this out of the box or if would have to provide a `Display` implementation for it.

This isn't critical, but worth looking into if it's easily fixable.

**Review by Malax — APPROVED** [review]
Well done! 👍🏻  I especially like the tests, they're neatly done!

File: libcnb-data/src/buildpack.rs (hunk 2 above)
Comment (edmorley) [reply libcnb-data/src/buildpack.rs]: It turns out thiserror does allow doing this :-)
ba185605446ffb82d923b6e136e3540e2bb6335d

Comment (Malax) [reply libcnb-data/src/buildpack.rs]: Awesome! Thanks for looking into it!
