### PR TITLE
Correct the data model for `buildpack.toml`

### LINKED ISSUE #211: `libcnb_data::buildpack::Buildpack` should not permit meta-buildpacks that define `stacks`
libcnb-data's `Buildpack` type permits (and actually requires) having both `stacks` and `order` defined (ie meta-buildpacks with `stacks`), however pack forbids this:

```
ERROR: failed to build: downloading buildpack: extracting from file:///Users/emorley/src/testcase: reading buildpack: invalid buildpack.toml: buildpack heroku/example@0.1.0: cannot have both stacks and an order defined
```

As does the spec, however the wording makes it hard to spot:

> A buildpack descriptor that specifies `order` MUST be resolvable into an ordering of buildpacks that implement the [Buildpack Interface](https://github.com/buildpacks/spec/blob/main/buildpack.md#buildpack-interface).

https://github.com/buildpacks/spec/blob/main/buildpack.md#buildpack-implementations

The "Buildpack Interface" means `bin/detect` etc, so excludes meta-buildpacks.

GUS-W-10289129.

### PR DESCRIPTION
**Pull request by edmorley**
The CNB spec states that a `buildpack.toml` must contain exactly one of the tables `stacks` or `order`, but not both - since they relate to different buildpack types (single buildpacks and meta-buildpacks respectively):
https://github.com/buildpacks/spec/blob/main/buildpack.md#buildpack-implementations

Previously `BuildpackToml` attempted to represent both of these as a single type, which both meant the type wasn't an accurate representation, but also that invalid `buildpack.toml` files would pass `libcnb package` validation only to fail later at runtime with a Pack CLI error message.

Now `BuildpackToml` has been replaced with the enum `BuildpackDescriptor`, which has `Single` and `Meta` variants that wrap new `SingleBuildpackDescriptor` and `MetaBuildpackDescriptor` types.

Consumers of libcnb-data can now either parse `buildpack.toml` files using `BuildpackDescriptor` when they wish to support both variants, or else use the specific sub-types when a specific buildpack type is required for improved error messages.

Fixes #211.
GUS-W-10289129.

### CODE REVIEW

**Comment by edmorley** [comment]
CI is failing due to the unrelated #249, which will be fixed by #250 (I'll rebase once that merges).

File: libcnb-data/src/buildpack/mod.rs [hunk 1]
```diff
@@ -34,22 +40,111 @@ use serde::Deserialize;
...
+/// match buildpack_toml {
+///     BuildpackToml::Single(buildpack) => println!("Found buildpack: {}", buildpack.buildpack.id),
+///     BuildpackToml::Meta(buildpack) => println!("Found meta-buildpack: {}", buildpack.buildpack.id),
+/// };
+/// ```
+#[derive(Deserialize, Debug)]
+#[serde(untagged)]
+pub enum BuildpackToml<BM> {
+    Single(SingleBuildpack<BM>),
+    Meta(MetaBuildpack<BM>),
```
Comment (Malax) [inline libcnb-data/src/buildpack/mod.rs:56]: I'm not yet sold on the naming of these types. I feel like this PR is a good opportunity to resolve #168, or at least finalize a naming for the types so we can change the variable names separately to match the type names.

Since at least `SingleBuildpack` is used standalone in buildpack implementations, I don't think it really conveys what it is. Granted, naming CNB related things is hard with all the overloaded terms in the spec. When I first read this in a context where `SingleBuildpack` is used standalone (later in this PR), I stopped for a moment, thinking "why does this function get a buildpack as an argument?".

If we'd want to keep the `BuildpackToml` naming for the composite type, I could see us using `SingleBuildpackToml` and `MetaBuildpackToml` for the variant structs.

In general, I think I don't like the `BuildpackToml` name so much and would prefer `BuildpackDescriptor` instead. `SingleBuildpackDescriptor` and `MetaBuildpackDescriptor` work fine for the variants IMO.

Comment (edmorley) [reply libcnb-data/src/buildpack/mod.rs:56]: Yeah I agree all of the names are suboptimal, and that the CNB spec doesn't make this easy.

I like the idea of `BuildpackDescriptor` / `SingleBuildpackDescriptor` / `MetaBuildpackDescriptor`.

The other type name that bugs me, is `libcnb_data::buildpack::Buildpack`, which is the `buildpack` table inside `buildpacks.toml`. My first thought was that we could name it `BuildpackMetadata`, but then we also have the `metadata` table which sounds too similar to that. Other options for that might be `BuildpackTable`, `BuildpackProperties` (but then what's the difference between "properties" and "metadata"?), `BuildpackDetails` etc.

I guess really `metadata` is "custom metadata" and the `buildpack` table is `BuildpackMetadata`?

Eugh

Comment (hone) [reply libcnb-data/src/buildpack/mod.rs:56]: I think I named it `BuildpackToml` so you can blame me for that. I agree that `BuildpackDescriptor` is the better name.

File: libcnb-data/src/buildpack/mod.rs [hunk 2]
```diff
@@ -34,22 +40,111 @@ use serde::Deserialize;
...
+/// let buildpack_toml = toml::from_str::<SingleBuildpack<Option<toml::value::Table>>>(toml_str).unwrap();
+/// assert_eq!(buildpack_toml.buildpack.id, buildpack_id!("foo/bar"));
+/// assert_eq!(buildpack_toml.stacks, vec![Stack::Any]);
 /// ```
 #[derive(Deserialize, Debug)]
-pub struct BuildpackToml<BM> {
+// `deny_unknown_fields` is required since otherwise a buildpack TOML with both
+// `stacks` and `order` will be deserialized into the first type that matches,
+// rather than being rejected for being invalid.
+#[serde(deny_unknown_fields)]
```
[the remark this answers is not in the document]
Comment (hone) [reply libcnb-data/src/buildpack/mod.rs:98]: I think we should, afaik all the field should be spec'd except for things like `[metadata]` tables.

**Comment by hone** [comment]
Besides the naming bikeshed this implementation looks good.

File: libcnb-data/src/buildpack/mod.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (edmorley) [reply libcnb-data/src/buildpack/mod.rs:98]: Yeah I agree

File: libcnb-data/src/buildpack/mod.rs (hunk 1 above)
Comment (Malax) [reply libcnb-data/src/buildpack/mod.rs:56]: `libcnb_data::buildpack::Buildpack` is something for another PR I guess?

Comment (edmorley) [reply libcnb-data/src/buildpack/mod.rs]: Types renamed in ed15a71.

File: libcnb-data/src/buildpack/mod.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (edmorley) [reply libcnb-data/src/buildpack/mod.rs:98]: Filed #251

**Review by Malax — APPROVED** [review]
Thank you! :shipit:
