### PR TITLE
Fix broken docs and add docs linting to CI

### LINKED ISSUE #247: "warning: unresolved link to `Display`" when running `cargo doc`
We really need CI for this.

```
$ cargo doc
...

warning: unresolved link to `Display`
  --> libcnb/src/buildpack.rs:45:22
   |
45 |     /// (using its [`Display`] implementation) to stderr.
   |                      ^^^^^^^ no item named `Display` in scope
   |
   = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: `libcnb` (lib doc) generated 1 warning
```

### PR DESCRIPTION
**Pull request by edmorley**
The Clippy lints already being run in CI check for a few docs related issues, however `rustdoc` has additional lints beyond that:
https://doc.rust-lang.org/rustdoc/lints.html

Several of these lints were reporting warnings when docs are built locally:

```
$ cargo doc --all-features --document-private-items --no-deps
...
warning: unresolved link to `Display`
 --> libcnb-data/src/newtypes.rs:6:9
  |
6 | /// - [`Display`]
  |         ^^^^^^^ no item named `Display` in scope
  |
  = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
  = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `FromStr`
  --> libcnb-data/src/newtypes.rs:11:9
   |
11 | /// - [`FromStr`]
   |         ^^^^^^^ no item named `FromStr` in scope
   |
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `Borrow`
  --> libcnb-data/src/newtypes.rs:12:9
   |
12 | /// - [`Borrow<String>`]
   |         ^^^^^^^^^^^^^^ no item named `Borrow` in scope
   |
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: `libcnb-data` (lib doc) generated 3 warnings
 Documenting example-01-basics v0.1.0 (/Users/emorley/src/libcnb.rs/examples/example-01-basics)
 Documenting example-02-ruby-sample v0.1.0 (/Users/emorley/src/libcnb.rs/examples/example-02-ruby-sample)
warning: unresolved link to `Display`
  --> libcnb/src/buildpack.rs:45:22
   |
45 |     /// (using its [`Display`] implementation) to stderr.
   |                      ^^^^^^^ no item named `Display` in scope
   |
   = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: `libcnb` (lib doc) generated 1 warning
```

These have now been fixed, and a docs check added to CI.

See also:
https://doc.rust-lang.org/cargo/commands/cargo-doc.html
https://doc.rust-lang.org/rustdoc/linking-to-items-by-name.html

Fixes #247.
GUS-W-10416368.

### CODE REVIEW

File: libcnb-data/src/newtypes.rs [hunk 1]
```diff
@@ -3,13 +3,14 @@
...
+/// - [`Display`](std::fmt::Display)
 /// - [`Eq`]
 /// - [`PartialEq`]
 /// - [`serde::Deserialize`]
 /// - [`serde::Serialize`]
-/// - [`FromStr`]
-/// - [`Borrow<String>`]
+/// - [`FromStr`](std::str::FromStr)
+/// - [`Borrow<String>`](std::borrow::Borrow<String>)
+/// - [`Borrow<str>`](std::borrow::Borrow<String>)
```
Comment (Malax) [inline libcnb-data/src/newtypes.rs:13]: Sneaky. ;-)

**Review by Malax — APPROVED** [review]

**Comment by Malax** [comment]
This is great to have! 👍🏻

File: libcnb-data/src/newtypes.rs (hunk 1 above)
Comment (edmorley) [reply libcnb-data/src/newtypes.rs:13]: This should also actually be `std::borrow::Borrow<str>` not `std::borrow::Borrow<String>` - I'll update now.
