### PR TITLE
Avoid undocumented panics and enable `clippy::missing-panics-doc`

### LINKED ISSUE #54: Fix clippy::missing-panics-doc warning
I ran Clippy's pedantic lints (which are disabled by default since they are typically subjective or have high false positive rates) against this repository out of curiosity, and am filing a few issues for some of the lints that warned that seemed relevant (in part to give some easy issues for people to work through to get involved with this library).

Feel free to close this out if not wanted :-)

See:
https://rust-lang.github.io/rust-clippy/master/index.html#missing_panics_doc
https://rust-lang.github.io/api-guidelines/documentation.html#function-docs-include-error-panic-and-safety-considerations-c-failure

```
$ cargo clippy --all-targets --all-features -- -W clippy::missing-panics-doc
    Checking libcnb v0.2.0 (/Users/emorley/src/libcnb.rs)
warning: docs for function which may panic missing `# Panics` section
   --> src/layer_env.rs:242:5
    |
242 | /     pub fn read_from_layer_dir(layer_dir: impl AsRef<Path>) -> Result<LayerEnv, std::io::Error> {
243 | |         let mut result_layer_env = LayerEnv::new();
244 | |
245 | |         let bin_path = layer_dir.as_ref().join("bin");
...   |
288 | |         Ok(result_layer_env)
289 | |     }
    | |_____^
    |
    = note: requested on the command line with `-W clippy::missing-panics-doc`
note: first possible panic found here
   --> src/layer_env.rs:265:26
    |
265 |                     _ => panic!("Unexpected TargetLifecycle in read_from_layer_dir implementation. This is a libcnb implementation error!"),
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_panics_doc
    = note: this warning originates in the macro `$crate::panic::panic_2015` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### PR DESCRIPTION
**Pull request by edmorley**
Switches the `panic!` in `LayerEnv::read_from_layer_dir()` to `unreachable!`, since:
- it more clearly indicates the intent (unreachable code unless there is a bug)
- it means we can globally enable the `clippy::missing-panics-doc` lint, without having to either:
  (a) add an unnecessary `# Panic` section to the docs (which would only add noise, given the caller needn't be aware of panics for internal bugs)
  (b) add an `#[allow(...)]` annotation to all of `read_from_layer_dir()`, which could mean future new undocumented panics aren't caught by clippy.

Fixes #54.

### CODE REVIEW

**Comment by edmorley** [comment]
(Though I still feel that perhaps `read_from_layer_dir()` / `layer_path_specs` could do with a types/approach refactor to avoid this unreachable branch in the first place, but not worth it for now)

File: libcnb/src/layer_env.rs [hunk 1]
```diff
@@ -262,7 +262,8 @@ impl LayerEnv {
                 let target_delta = match target_lifecycle {
                     TargetLifecycle::Build => &mut result_layer_env.layer_paths_build,
                     TargetLifecycle::Launch => &mut result_layer_env.layer_paths_launch,
-                    _ => panic!("Unexpected TargetLifecycle in read_from_layer_dir implementation. This is a libcnb implementation error!"),
+                    // Other `TargetLifecycle` variants are not valid in `layer_path_specs` and would indicate a libcnb bug.
+                    _ => unreachable!(),
```
Comment (Malax) [inline libcnb/src/layer_env.rs:266]: Do we want to keep the previous message? It would ease debugging should that match arm ever match.

```suggestion
                    _ => unreachable!("Unexpected TargetLifecycle in read_from_layer_dir implementation. This is a libcnb implementation error!"),
```

**Review by Malax — APPROVED** [review]

File: libcnb/src/layer_env.rs (hunk 1 above)
Comment (edmorley) [reply libcnb/src/layer_env.rs:266]: @Malax Ah! I didn't know a custom message was possible with `unreachable!` since the docs don't mention it (and I wasn't yet familiar with the nuances of `macro_rules` syntax; I've now read up on that):
https://doc.rust-lang.org/core/macro.unreachable.html

I've opened an upstream PR to improve the docs:
https://github.com/rust-lang/rust/pull/90798
